//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace sacis.view.control.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testeOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastraUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastraContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeContatoPessoalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::sacis.view.control.Properties.Settings.Default.sacis_view_control_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testeCompletedEventHandler testeCompleted;
        
        /// <remarks/>
        public event verificaUsuarioCompletedEventHandler verificaUsuarioCompleted;
        
        /// <remarks/>
        public event cadastraUsuarioCompletedEventHandler cadastraUsuarioCompleted;
        
        /// <remarks/>
        public event consultaUsuarioCompletedEventHandler consultaUsuarioCompleted;
        
        /// <remarks/>
        public event retornaContatosCompletedEventHandler retornaContatosCompleted;
        
        /// <remarks/>
        public event cadastraContatoPessoalCompletedEventHandler cadastraContatoPessoalCompleted;
        
        /// <remarks/>
        public event retornaContatoPessoalCompletedEventHandler retornaContatoPessoalCompleted;
        
        /// <remarks/>
        public event removeContatoPessoalCompletedEventHandler removeContatoPessoalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/teste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string teste() {
            object[] results = this.Invoke("teste", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testeAsync() {
            this.testeAsync(null);
        }
        
        /// <remarks/>
        public void testeAsync(object userState) {
            if ((this.testeOperationCompleted == null)) {
                this.testeOperationCompleted = new System.Threading.SendOrPostCallback(this.OntesteOperationCompleted);
            }
            this.InvokeAsync("teste", new object[0], this.testeOperationCompleted, userState);
        }
        
        private void OntesteOperationCompleted(object arg) {
            if ((this.testeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testeCompleted(this, new testeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificaUsuario(string login) {
            object[] results = this.Invoke("verificaUsuario", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login) {
            this.verificaUsuarioAsync(login, null);
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login, object userState) {
            if ((this.verificaUsuarioOperationCompleted == null)) {
                this.verificaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificaUsuario", new object[] {
                        login}, this.verificaUsuarioOperationCompleted, userState);
        }
        
        private void OnverificaUsuarioOperationCompleted(object arg) {
            if ((this.verificaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaUsuarioCompleted(this, new verificaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cadastraUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cadastraUsuario(string xmluser) {
            this.Invoke("cadastraUsuario", new object[] {
                        xmluser});
        }
        
        /// <remarks/>
        public void cadastraUsuarioAsync(string xmluser) {
            this.cadastraUsuarioAsync(xmluser, null);
        }
        
        /// <remarks/>
        public void cadastraUsuarioAsync(string xmluser, object userState) {
            if ((this.cadastraUsuarioOperationCompleted == null)) {
                this.cadastraUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastraUsuarioOperationCompleted);
            }
            this.InvokeAsync("cadastraUsuario", new object[] {
                        xmluser}, this.cadastraUsuarioOperationCompleted, userState);
        }
        
        private void OncadastraUsuarioOperationCompleted(object arg) {
            if ((this.cadastraUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastraUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool consultaUsuario(string login, string senha) {
            object[] results = this.Invoke("consultaUsuario", new object[] {
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha) {
            this.consultaUsuarioAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha, object userState) {
            if ((this.consultaUsuarioOperationCompleted == null)) {
                this.consultaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultaUsuario", new object[] {
                        login,
                        senha}, this.consultaUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultaUsuarioOperationCompleted(object arg) {
            if ((this.consultaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaUsuarioCompleted(this, new consultaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornaContatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContatos() {
            object[] results = this.Invoke("retornaContatos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatosAsync() {
            this.retornaContatosAsync(null);
        }
        
        /// <remarks/>
        public void retornaContatosAsync(object userState) {
            if ((this.retornaContatosOperationCompleted == null)) {
                this.retornaContatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatosOperationCompleted);
            }
            this.InvokeAsync("retornaContatos", new object[0], this.retornaContatosOperationCompleted, userState);
        }
        
        private void OnretornaContatosOperationCompleted(object arg) {
            if ((this.retornaContatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatosCompleted(this, new retornaContatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cadastraContatoPessoal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cadastraContatoPessoal(string xml, string user) {
            object[] results = this.Invoke("cadastraContatoPessoal", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cadastraContatoPessoalAsync(string xml, string user) {
            this.cadastraContatoPessoalAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void cadastraContatoPessoalAsync(string xml, string user, object userState) {
            if ((this.cadastraContatoPessoalOperationCompleted == null)) {
                this.cadastraContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastraContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("cadastraContatoPessoal", new object[] {
                        xml,
                        user}, this.cadastraContatoPessoalOperationCompleted, userState);
        }
        
        private void OncadastraContatoPessoalOperationCompleted(object arg) {
            if ((this.cadastraContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastraContatoPessoalCompleted(this, new cadastraContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornaContatoPessoal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContatoPessoal(string user) {
            object[] results = this.Invoke("retornaContatoPessoal", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user) {
            this.retornaContatoPessoalAsync(user, null);
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user, object userState) {
            if ((this.retornaContatoPessoalOperationCompleted == null)) {
                this.retornaContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("retornaContatoPessoal", new object[] {
                        user}, this.retornaContatoPessoalOperationCompleted, userState);
        }
        
        private void OnretornaContatoPessoalOperationCompleted(object arg) {
            if ((this.retornaContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatoPessoalCompleted(this, new retornaContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/removeContatoPessoal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool removeContatoPessoal(string xml, string user) {
            object[] results = this.Invoke("removeContatoPessoal", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeContatoPessoalAsync(string xml, string user) {
            this.removeContatoPessoalAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void removeContatoPessoalAsync(string xml, string user, object userState) {
            if ((this.removeContatoPessoalOperationCompleted == null)) {
                this.removeContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("removeContatoPessoal", new object[] {
                        xml,
                        user}, this.removeContatoPessoalOperationCompleted, userState);
        }
        
        private void OnremoveContatoPessoalOperationCompleted(object arg) {
            if ((this.removeContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeContatoPessoalCompleted(this, new removeContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void testeCompletedEventHandler(object sender, testeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void verificaUsuarioCompletedEventHandler(object sender, verificaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastraUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void consultaUsuarioCompletedEventHandler(object sender, consultaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatosCompletedEventHandler(object sender, retornaContatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastraContatoPessoalCompletedEventHandler(object sender, cadastraContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cadastraContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cadastraContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatoPessoalCompletedEventHandler(object sender, retornaContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void removeContatoPessoalCompletedEventHandler(object sender, removeContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591