//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace sacis.view.control.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback verificaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastramentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastraContatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeContatoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::sacis.view.control.Properties.Settings.Default.sacis_view_control_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event verificaUsuarioCompletedEventHandler verificaUsuarioCompleted;
        
        /// <remarks/>
        public event cadastramentoCompletedEventHandler cadastramentoCompleted;
        
        /// <remarks/>
        public event consultaUsuarioCompletedEventHandler consultaUsuarioCompleted;
        
        /// <remarks/>
        public event retornaContatoCompletedEventHandler retornaContatoCompleted;
        
        /// <remarks/>
        public event cadastraContatoCompletedEventHandler cadastraContatoCompleted;
        
        /// <remarks/>
        public event retornaContatoPessoalCompletedEventHandler retornaContatoPessoalCompleted;
        
        /// <remarks/>
        public event removeContatoCompletedEventHandler removeContatoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificaUsuario(string login) {
            object[] results = this.Invoke("verificaUsuario", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login) {
            this.verificaUsuarioAsync(login, null);
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login, object userState) {
            if ((this.verificaUsuarioOperationCompleted == null)) {
                this.verificaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificaUsuario", new object[] {
                        login}, this.verificaUsuarioOperationCompleted, userState);
        }
        
        private void OnverificaUsuarioOperationCompleted(object arg) {
            if ((this.verificaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaUsuarioCompleted(this, new verificaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cadastramento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cadastramento(string xmluser) {
            this.Invoke("cadastramento", new object[] {
                        xmluser});
        }
        
        /// <remarks/>
        public void cadastramentoAsync(string xmluser) {
            this.cadastramentoAsync(xmluser, null);
        }
        
        /// <remarks/>
        public void cadastramentoAsync(string xmluser, object userState) {
            if ((this.cadastramentoOperationCompleted == null)) {
                this.cadastramentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastramentoOperationCompleted);
            }
            this.InvokeAsync("cadastramento", new object[] {
                        xmluser}, this.cadastramentoOperationCompleted, userState);
        }
        
        private void OncadastramentoOperationCompleted(object arg) {
            if ((this.cadastramentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastramentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool consultaUsuario(string login, string senha) {
            object[] results = this.Invoke("consultaUsuario", new object[] {
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha) {
            this.consultaUsuarioAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha, object userState) {
            if ((this.consultaUsuarioOperationCompleted == null)) {
                this.consultaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultaUsuario", new object[] {
                        login,
                        senha}, this.consultaUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultaUsuarioOperationCompleted(object arg) {
            if ((this.consultaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaUsuarioCompleted(this, new consultaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornaContato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContato() {
            object[] results = this.Invoke("retornaContato", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatoAsync() {
            this.retornaContatoAsync(null);
        }
        
        /// <remarks/>
        public void retornaContatoAsync(object userState) {
            if ((this.retornaContatoOperationCompleted == null)) {
                this.retornaContatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatoOperationCompleted);
            }
            this.InvokeAsync("retornaContato", new object[0], this.retornaContatoOperationCompleted, userState);
        }
        
        private void OnretornaContatoOperationCompleted(object arg) {
            if ((this.retornaContatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatoCompleted(this, new retornaContatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cadastraContato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cadastraContato(string xml, string user) {
            object[] results = this.Invoke("cadastraContato", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cadastraContatoAsync(string xml, string user) {
            this.cadastraContatoAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void cadastraContatoAsync(string xml, string user, object userState) {
            if ((this.cadastraContatoOperationCompleted == null)) {
                this.cadastraContatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastraContatoOperationCompleted);
            }
            this.InvokeAsync("cadastraContato", new object[] {
                        xml,
                        user}, this.cadastraContatoOperationCompleted, userState);
        }
        
        private void OncadastraContatoOperationCompleted(object arg) {
            if ((this.cadastraContatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastraContatoCompleted(this, new cadastraContatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornaContatoPessoal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContatoPessoal(string user) {
            object[] results = this.Invoke("retornaContatoPessoal", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user) {
            this.retornaContatoPessoalAsync(user, null);
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user, object userState) {
            if ((this.retornaContatoPessoalOperationCompleted == null)) {
                this.retornaContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("retornaContatoPessoal", new object[] {
                        user}, this.retornaContatoPessoalOperationCompleted, userState);
        }
        
        private void OnretornaContatoPessoalOperationCompleted(object arg) {
            if ((this.retornaContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatoPessoalCompleted(this, new retornaContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/removeContato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool removeContato(string xml, string user) {
            object[] results = this.Invoke("removeContato", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeContatoAsync(string xml, string user) {
            this.removeContatoAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void removeContatoAsync(string xml, string user, object userState) {
            if ((this.removeContatoOperationCompleted == null)) {
                this.removeContatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveContatoOperationCompleted);
            }
            this.InvokeAsync("removeContato", new object[] {
                        xml,
                        user}, this.removeContatoOperationCompleted, userState);
        }
        
        private void OnremoveContatoOperationCompleted(object arg) {
            if ((this.removeContatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeContatoCompleted(this, new removeContatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void verificaUsuarioCompletedEventHandler(object sender, verificaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastramentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void consultaUsuarioCompletedEventHandler(object sender, consultaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatoCompletedEventHandler(object sender, retornaContatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastraContatoCompletedEventHandler(object sender, cadastraContatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cadastraContatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cadastraContatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatoPessoalCompletedEventHandler(object sender, retornaContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void removeContatoCompletedEventHandler(object sender, removeContatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeContatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeContatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591