//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace sacis.view.control.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://sacis.com.br")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback verificaLoginUsuarioManutencaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetaSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraNomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraPermissaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraCertificadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluiUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastraUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastraContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeContatoPessoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviaMensagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaCabecalhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback apagaMensagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaMensagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaAnexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback abreAnexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaChavePublicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificaMensagemCriptografadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::sacis.view.control.Properties.Settings.Default.sacis_view_control_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event verificaLoginUsuarioManutencaoCompletedEventHandler verificaLoginUsuarioManutencaoCompleted;
        
        /// <remarks/>
        public event verificaUsuarioCompletedEventHandler verificaUsuarioCompleted;
        
        /// <remarks/>
        public event resetaSenhaCompletedEventHandler resetaSenhaCompleted;
        
        /// <remarks/>
        public event alteraNomeCompletedEventHandler alteraNomeCompleted;
        
        /// <remarks/>
        public event alteraPermissaoCompletedEventHandler alteraPermissaoCompleted;
        
        /// <remarks/>
        public event alteraCertificadoCompletedEventHandler alteraCertificadoCompleted;
        
        /// <remarks/>
        public event excluiUsuarioCompletedEventHandler excluiUsuarioCompleted;
        
        /// <remarks/>
        public event cadastraUsuarioCompletedEventHandler cadastraUsuarioCompleted;
        
        /// <remarks/>
        public event consultaUsuarioCompletedEventHandler consultaUsuarioCompleted;
        
        /// <remarks/>
        public event alteraSenhaCompletedEventHandler alteraSenhaCompleted;
        
        /// <remarks/>
        public event retornaContatosCompletedEventHandler retornaContatosCompleted;
        
        /// <remarks/>
        public event cadastraContatoPessoalCompletedEventHandler cadastraContatoPessoalCompleted;
        
        /// <remarks/>
        public event retornaContatoPessoalCompletedEventHandler retornaContatoPessoalCompleted;
        
        /// <remarks/>
        public event removeContatoPessoalCompletedEventHandler removeContatoPessoalCompleted;
        
        /// <remarks/>
        public event enviaMensagemCompletedEventHandler enviaMensagemCompleted;
        
        /// <remarks/>
        public event retornaCabecalhoCompletedEventHandler retornaCabecalhoCompleted;
        
        /// <remarks/>
        public event apagaMensagemCompletedEventHandler apagaMensagemCompleted;
        
        /// <remarks/>
        public event buscaMensagemCompletedEventHandler buscaMensagemCompleted;
        
        /// <remarks/>
        public event buscaAnexoCompletedEventHandler buscaAnexoCompleted;
        
        /// <remarks/>
        public event abreAnexoCompletedEventHandler abreAnexoCompleted;
        
        /// <remarks/>
        public event retornaChavePublicaCompletedEventHandler retornaChavePublicaCompleted;
        
        /// <remarks/>
        public event verificaMensagemCriptografadaCompletedEventHandler verificaMensagemCriptografadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/verificaLoginUsuarioManutencao", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificaLoginUsuarioManutencao(string login, string senha) {
            object[] results = this.Invoke("verificaLoginUsuarioManutencao", new object[] {
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificaLoginUsuarioManutencaoAsync(string login, string senha) {
            this.verificaLoginUsuarioManutencaoAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void verificaLoginUsuarioManutencaoAsync(string login, string senha, object userState) {
            if ((this.verificaLoginUsuarioManutencaoOperationCompleted == null)) {
                this.verificaLoginUsuarioManutencaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaLoginUsuarioManutencaoOperationCompleted);
            }
            this.InvokeAsync("verificaLoginUsuarioManutencao", new object[] {
                        login,
                        senha}, this.verificaLoginUsuarioManutencaoOperationCompleted, userState);
        }
        
        private void OnverificaLoginUsuarioManutencaoOperationCompleted(object arg) {
            if ((this.verificaLoginUsuarioManutencaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaLoginUsuarioManutencaoCompleted(this, new verificaLoginUsuarioManutencaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/verificaUsuario", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificaUsuario(string login) {
            object[] results = this.Invoke("verificaUsuario", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login) {
            this.verificaUsuarioAsync(login, null);
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string login, object userState) {
            if ((this.verificaUsuarioOperationCompleted == null)) {
                this.verificaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificaUsuario", new object[] {
                        login}, this.verificaUsuarioOperationCompleted, userState);
        }
        
        private void OnverificaUsuarioOperationCompleted(object arg) {
            if ((this.verificaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaUsuarioCompleted(this, new verificaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/resetaSenha", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool resetaSenha(string login) {
            object[] results = this.Invoke("resetaSenha", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void resetaSenhaAsync(string login) {
            this.resetaSenhaAsync(login, null);
        }
        
        /// <remarks/>
        public void resetaSenhaAsync(string login, object userState) {
            if ((this.resetaSenhaOperationCompleted == null)) {
                this.resetaSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetaSenhaOperationCompleted);
            }
            this.InvokeAsync("resetaSenha", new object[] {
                        login}, this.resetaSenhaOperationCompleted, userState);
        }
        
        private void OnresetaSenhaOperationCompleted(object arg) {
            if ((this.resetaSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetaSenhaCompleted(this, new resetaSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/alteraNome", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alteraNome(string login, string nome) {
            object[] results = this.Invoke("alteraNome", new object[] {
                        login,
                        nome});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alteraNomeAsync(string login, string nome) {
            this.alteraNomeAsync(login, nome, null);
        }
        
        /// <remarks/>
        public void alteraNomeAsync(string login, string nome, object userState) {
            if ((this.alteraNomeOperationCompleted == null)) {
                this.alteraNomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraNomeOperationCompleted);
            }
            this.InvokeAsync("alteraNome", new object[] {
                        login,
                        nome}, this.alteraNomeOperationCompleted, userState);
        }
        
        private void OnalteraNomeOperationCompleted(object arg) {
            if ((this.alteraNomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraNomeCompleted(this, new alteraNomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/alteraPermissao", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alteraPermissao(string login, int permissao) {
            object[] results = this.Invoke("alteraPermissao", new object[] {
                        login,
                        permissao});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alteraPermissaoAsync(string login, int permissao) {
            this.alteraPermissaoAsync(login, permissao, null);
        }
        
        /// <remarks/>
        public void alteraPermissaoAsync(string login, int permissao, object userState) {
            if ((this.alteraPermissaoOperationCompleted == null)) {
                this.alteraPermissaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraPermissaoOperationCompleted);
            }
            this.InvokeAsync("alteraPermissao", new object[] {
                        login,
                        permissao}, this.alteraPermissaoOperationCompleted, userState);
        }
        
        private void OnalteraPermissaoOperationCompleted(object arg) {
            if ((this.alteraPermissaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraPermissaoCompleted(this, new alteraPermissaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/alteraCertificado", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alteraCertificado(string login, string certificado, string validade) {
            object[] results = this.Invoke("alteraCertificado", new object[] {
                        login,
                        certificado,
                        validade});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alteraCertificadoAsync(string login, string certificado, string validade) {
            this.alteraCertificadoAsync(login, certificado, validade, null);
        }
        
        /// <remarks/>
        public void alteraCertificadoAsync(string login, string certificado, string validade, object userState) {
            if ((this.alteraCertificadoOperationCompleted == null)) {
                this.alteraCertificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraCertificadoOperationCompleted);
            }
            this.InvokeAsync("alteraCertificado", new object[] {
                        login,
                        certificado,
                        validade}, this.alteraCertificadoOperationCompleted, userState);
        }
        
        private void OnalteraCertificadoOperationCompleted(object arg) {
            if ((this.alteraCertificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraCertificadoCompleted(this, new alteraCertificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/excluiUsuario", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool excluiUsuario(string login) {
            object[] results = this.Invoke("excluiUsuario", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void excluiUsuarioAsync(string login) {
            this.excluiUsuarioAsync(login, null);
        }
        
        /// <remarks/>
        public void excluiUsuarioAsync(string login, object userState) {
            if ((this.excluiUsuarioOperationCompleted == null)) {
                this.excluiUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluiUsuarioOperationCompleted);
            }
            this.InvokeAsync("excluiUsuario", new object[] {
                        login}, this.excluiUsuarioOperationCompleted, userState);
        }
        
        private void OnexcluiUsuarioOperationCompleted(object arg) {
            if ((this.excluiUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluiUsuarioCompleted(this, new excluiUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/cadastraUsuario", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cadastraUsuario(string xmluser) {
            this.Invoke("cadastraUsuario", new object[] {
                        xmluser});
        }
        
        /// <remarks/>
        public void cadastraUsuarioAsync(string xmluser) {
            this.cadastraUsuarioAsync(xmluser, null);
        }
        
        /// <remarks/>
        public void cadastraUsuarioAsync(string xmluser, object userState) {
            if ((this.cadastraUsuarioOperationCompleted == null)) {
                this.cadastraUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastraUsuarioOperationCompleted);
            }
            this.InvokeAsync("cadastraUsuario", new object[] {
                        xmluser}, this.cadastraUsuarioOperationCompleted, userState);
        }
        
        private void OncadastraUsuarioOperationCompleted(object arg) {
            if ((this.cadastraUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastraUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/consultaUsuario", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int consultaUsuario(string login, string senha) {
            object[] results = this.Invoke("consultaUsuario", new object[] {
                        login,
                        senha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha) {
            this.consultaUsuarioAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string login, string senha, object userState) {
            if ((this.consultaUsuarioOperationCompleted == null)) {
                this.consultaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultaUsuario", new object[] {
                        login,
                        senha}, this.consultaUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultaUsuarioOperationCompleted(object arg) {
            if ((this.consultaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaUsuarioCompleted(this, new consultaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/alteraSenha", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alteraSenha(string login, string senha) {
            object[] results = this.Invoke("alteraSenha", new object[] {
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alteraSenhaAsync(string login, string senha) {
            this.alteraSenhaAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void alteraSenhaAsync(string login, string senha, object userState) {
            if ((this.alteraSenhaOperationCompleted == null)) {
                this.alteraSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraSenhaOperationCompleted);
            }
            this.InvokeAsync("alteraSenha", new object[] {
                        login,
                        senha}, this.alteraSenhaOperationCompleted, userState);
        }
        
        private void OnalteraSenhaOperationCompleted(object arg) {
            if ((this.alteraSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraSenhaCompleted(this, new alteraSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/retornaContatos", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContatos() {
            object[] results = this.Invoke("retornaContatos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatosAsync() {
            this.retornaContatosAsync(null);
        }
        
        /// <remarks/>
        public void retornaContatosAsync(object userState) {
            if ((this.retornaContatosOperationCompleted == null)) {
                this.retornaContatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatosOperationCompleted);
            }
            this.InvokeAsync("retornaContatos", new object[0], this.retornaContatosOperationCompleted, userState);
        }
        
        private void OnretornaContatosOperationCompleted(object arg) {
            if ((this.retornaContatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatosCompleted(this, new retornaContatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/cadastraContatoPessoal", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cadastraContatoPessoal(string xml, string user) {
            object[] results = this.Invoke("cadastraContatoPessoal", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cadastraContatoPessoalAsync(string xml, string user) {
            this.cadastraContatoPessoalAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void cadastraContatoPessoalAsync(string xml, string user, object userState) {
            if ((this.cadastraContatoPessoalOperationCompleted == null)) {
                this.cadastraContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastraContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("cadastraContatoPessoal", new object[] {
                        xml,
                        user}, this.cadastraContatoPessoalOperationCompleted, userState);
        }
        
        private void OncadastraContatoPessoalOperationCompleted(object arg) {
            if ((this.cadastraContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastraContatoPessoalCompleted(this, new cadastraContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/retornaContatoPessoal", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaContatoPessoal(string user) {
            object[] results = this.Invoke("retornaContatoPessoal", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user) {
            this.retornaContatoPessoalAsync(user, null);
        }
        
        /// <remarks/>
        public void retornaContatoPessoalAsync(string user, object userState) {
            if ((this.retornaContatoPessoalOperationCompleted == null)) {
                this.retornaContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("retornaContatoPessoal", new object[] {
                        user}, this.retornaContatoPessoalOperationCompleted, userState);
        }
        
        private void OnretornaContatoPessoalOperationCompleted(object arg) {
            if ((this.retornaContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaContatoPessoalCompleted(this, new retornaContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/removeContatoPessoal", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool removeContatoPessoal(string xml, string user) {
            object[] results = this.Invoke("removeContatoPessoal", new object[] {
                        xml,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeContatoPessoalAsync(string xml, string user) {
            this.removeContatoPessoalAsync(xml, user, null);
        }
        
        /// <remarks/>
        public void removeContatoPessoalAsync(string xml, string user, object userState) {
            if ((this.removeContatoPessoalOperationCompleted == null)) {
                this.removeContatoPessoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveContatoPessoalOperationCompleted);
            }
            this.InvokeAsync("removeContatoPessoal", new object[] {
                        xml,
                        user}, this.removeContatoPessoalOperationCompleted, userState);
        }
        
        private void OnremoveContatoPessoalOperationCompleted(object arg) {
            if ((this.removeContatoPessoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeContatoPessoalCompleted(this, new removeContatoPessoalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/enviaMensagem", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool enviaMensagem(string xml) {
            object[] results = this.Invoke("enviaMensagem", new object[] {
                        xml});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void enviaMensagemAsync(string xml) {
            this.enviaMensagemAsync(xml, null);
        }
        
        /// <remarks/>
        public void enviaMensagemAsync(string xml, object userState) {
            if ((this.enviaMensagemOperationCompleted == null)) {
                this.enviaMensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviaMensagemOperationCompleted);
            }
            this.InvokeAsync("enviaMensagem", new object[] {
                        xml}, this.enviaMensagemOperationCompleted, userState);
        }
        
        private void OnenviaMensagemOperationCompleted(object arg) {
            if ((this.enviaMensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviaMensagemCompleted(this, new enviaMensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/retornaCabecalho", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaCabecalho(string login, string tipo) {
            object[] results = this.Invoke("retornaCabecalho", new object[] {
                        login,
                        tipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaCabecalhoAsync(string login, string tipo) {
            this.retornaCabecalhoAsync(login, tipo, null);
        }
        
        /// <remarks/>
        public void retornaCabecalhoAsync(string login, string tipo, object userState) {
            if ((this.retornaCabecalhoOperationCompleted == null)) {
                this.retornaCabecalhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaCabecalhoOperationCompleted);
            }
            this.InvokeAsync("retornaCabecalho", new object[] {
                        login,
                        tipo}, this.retornaCabecalhoOperationCompleted, userState);
        }
        
        private void OnretornaCabecalhoOperationCompleted(object arg) {
            if ((this.retornaCabecalhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaCabecalhoCompleted(this, new retornaCabecalhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/apagaMensagem", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool apagaMensagem(int id) {
            object[] results = this.Invoke("apagaMensagem", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void apagaMensagemAsync(int id) {
            this.apagaMensagemAsync(id, null);
        }
        
        /// <remarks/>
        public void apagaMensagemAsync(int id, object userState) {
            if ((this.apagaMensagemOperationCompleted == null)) {
                this.apagaMensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnapagaMensagemOperationCompleted);
            }
            this.InvokeAsync("apagaMensagem", new object[] {
                        id}, this.apagaMensagemOperationCompleted, userState);
        }
        
        private void OnapagaMensagemOperationCompleted(object arg) {
            if ((this.apagaMensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.apagaMensagemCompleted(this, new apagaMensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/buscaMensagem", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string buscaMensagem(int id) {
            object[] results = this.Invoke("buscaMensagem", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscaMensagemAsync(int id) {
            this.buscaMensagemAsync(id, null);
        }
        
        /// <remarks/>
        public void buscaMensagemAsync(int id, object userState) {
            if ((this.buscaMensagemOperationCompleted == null)) {
                this.buscaMensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaMensagemOperationCompleted);
            }
            this.InvokeAsync("buscaMensagem", new object[] {
                        id}, this.buscaMensagemOperationCompleted, userState);
        }
        
        private void OnbuscaMensagemOperationCompleted(object arg) {
            if ((this.buscaMensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaMensagemCompleted(this, new buscaMensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/buscaAnexo", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string buscaAnexo(int id) {
            object[] results = this.Invoke("buscaAnexo", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscaAnexoAsync(int id) {
            this.buscaAnexoAsync(id, null);
        }
        
        /// <remarks/>
        public void buscaAnexoAsync(int id, object userState) {
            if ((this.buscaAnexoOperationCompleted == null)) {
                this.buscaAnexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaAnexoOperationCompleted);
            }
            this.InvokeAsync("buscaAnexo", new object[] {
                        id}, this.buscaAnexoOperationCompleted, userState);
        }
        
        private void OnbuscaAnexoOperationCompleted(object arg) {
            if ((this.buscaAnexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaAnexoCompleted(this, new buscaAnexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/abreAnexo", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string abreAnexo(string nomeArq, int id) {
            object[] results = this.Invoke("abreAnexo", new object[] {
                        nomeArq,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void abreAnexoAsync(string nomeArq, int id) {
            this.abreAnexoAsync(nomeArq, id, null);
        }
        
        /// <remarks/>
        public void abreAnexoAsync(string nomeArq, int id, object userState) {
            if ((this.abreAnexoOperationCompleted == null)) {
                this.abreAnexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnabreAnexoOperationCompleted);
            }
            this.InvokeAsync("abreAnexo", new object[] {
                        nomeArq,
                        id}, this.abreAnexoOperationCompleted, userState);
        }
        
        private void OnabreAnexoOperationCompleted(object arg) {
            if ((this.abreAnexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.abreAnexoCompleted(this, new abreAnexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/retornaChavePublica", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retornaChavePublica(string destinatario) {
            object[] results = this.Invoke("retornaChavePublica", new object[] {
                        destinatario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retornaChavePublicaAsync(string destinatario) {
            this.retornaChavePublicaAsync(destinatario, null);
        }
        
        /// <remarks/>
        public void retornaChavePublicaAsync(string destinatario, object userState) {
            if ((this.retornaChavePublicaOperationCompleted == null)) {
                this.retornaChavePublicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaChavePublicaOperationCompleted);
            }
            this.InvokeAsync("retornaChavePublica", new object[] {
                        destinatario}, this.retornaChavePublicaOperationCompleted, userState);
        }
        
        private void OnretornaChavePublicaOperationCompleted(object arg) {
            if ((this.retornaChavePublicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaChavePublicaCompleted(this, new retornaChavePublicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sacis.com.br/verificaMensagemCriptografada", RequestNamespace="http://sacis.com.br", ResponseNamespace="http://sacis.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificaMensagemCriptografada(int id) {
            object[] results = this.Invoke("verificaMensagemCriptografada", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificaMensagemCriptografadaAsync(int id) {
            this.verificaMensagemCriptografadaAsync(id, null);
        }
        
        /// <remarks/>
        public void verificaMensagemCriptografadaAsync(int id, object userState) {
            if ((this.verificaMensagemCriptografadaOperationCompleted == null)) {
                this.verificaMensagemCriptografadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaMensagemCriptografadaOperationCompleted);
            }
            this.InvokeAsync("verificaMensagemCriptografada", new object[] {
                        id}, this.verificaMensagemCriptografadaOperationCompleted, userState);
        }
        
        private void OnverificaMensagemCriptografadaOperationCompleted(object arg) {
            if ((this.verificaMensagemCriptografadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaMensagemCriptografadaCompleted(this, new verificaMensagemCriptografadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void verificaLoginUsuarioManutencaoCompletedEventHandler(object sender, verificaLoginUsuarioManutencaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaLoginUsuarioManutencaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaLoginUsuarioManutencaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void verificaUsuarioCompletedEventHandler(object sender, verificaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void resetaSenhaCompletedEventHandler(object sender, resetaSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetaSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetaSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void alteraNomeCompletedEventHandler(object sender, alteraNomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alteraNomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alteraNomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void alteraPermissaoCompletedEventHandler(object sender, alteraPermissaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alteraPermissaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alteraPermissaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void alteraCertificadoCompletedEventHandler(object sender, alteraCertificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alteraCertificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alteraCertificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void excluiUsuarioCompletedEventHandler(object sender, excluiUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class excluiUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal excluiUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastraUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void consultaUsuarioCompletedEventHandler(object sender, consultaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void alteraSenhaCompletedEventHandler(object sender, alteraSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alteraSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alteraSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatosCompletedEventHandler(object sender, retornaContatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void cadastraContatoPessoalCompletedEventHandler(object sender, cadastraContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cadastraContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cadastraContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaContatoPessoalCompletedEventHandler(object sender, retornaContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void removeContatoPessoalCompletedEventHandler(object sender, removeContatoPessoalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeContatoPessoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeContatoPessoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void enviaMensagemCompletedEventHandler(object sender, enviaMensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviaMensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviaMensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaCabecalhoCompletedEventHandler(object sender, retornaCabecalhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaCabecalhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaCabecalhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void apagaMensagemCompletedEventHandler(object sender, apagaMensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class apagaMensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal apagaMensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void buscaMensagemCompletedEventHandler(object sender, buscaMensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaMensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaMensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void buscaAnexoCompletedEventHandler(object sender, buscaAnexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaAnexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaAnexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void abreAnexoCompletedEventHandler(object sender, abreAnexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class abreAnexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal abreAnexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void retornaChavePublicaCompletedEventHandler(object sender, retornaChavePublicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaChavePublicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaChavePublicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void verificaMensagemCriptografadaCompletedEventHandler(object sender, verificaMensagemCriptografadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaMensagemCriptografadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaMensagemCriptografadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591